stages:
  - build 
  - test 
  - end 


build:
  tags: 
    - gitlab-org-docker
  stage: build
  image: node:latest
  script:
    - npm install
    - npm start &

test:
  stage: test
  image:
    name: owasp/zap2docker-stable:latest
    entrypoint: [""]
  variables:
    CI_PROJECT_DIR: path_to_project_dir
    ZAP_ALERT_REPORT: alert-report
    ZAP_REPORT: baselinescan
  script:
    - ls
    - pwd
    - /zap/zap.sh -cmd -autorun npm-web-app.yaml
  only:
    refs:
    - branches
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - ${CI_PROJECT_DIR}/${ZAP_REPORT}.html
      - ${CI_PROJECT_DIR}/${ZAP_ALERT_REPORT}.md
