---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://NPM:3000"
    includePaths: []
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
  name: "spider"
  type: "spider"
- parameters:
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 32
    inScopeOnly: true
    excludedElements: []
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
  name: "spiderAjax"
  type: "spiderAjax"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    template: "traditional-html"
    reportDir: "/zap"
    reportFile: "ZAP_REPORT"
    reportTitle: "ZAP Baseline Scan Report"
    reportDescription: ""
    displayReport: false
  risks:
    - "info"
    - "low"
    - "medium"
    - "high"
  confidences:
    - "falsepositive"
    - "low"
    - "medium"
    - "high"
    - "confirmed"
  sections:
    - "instancecount"
    - "alertdetails"
    - "alertcount"
  name: "report"
  type: "report"
- parameters:
    template: "traditional-md"
    reportDir: "/zap"
    reportFile: "ZAP_ALERT_REPORT"
    reportTitle: "ZAP Scanning Report"
    reportDescription: "This is report that should contain only alerts that should\
      \ fail the pipeline and be revisited by a team member"
    displayReport: false
  risks:
    - "low"
    - "medium"
    - "high"
  confidences:
    - "low"
    - "medium"
    - "high"
    - "confirmed"
  sections:
    - "alertdetails"
    - "alertcount"
  name: "alert-report"
  type: "report"

